package httpapi

// Descriptions of types and fields in the OpenAPI document. Names and types
// come from the Go types (openapi_schema.go); only the words are here.
// Key: "TypeName.jsonName".

var typeDocs = map[string]string{
	"Device":       "One device of the list: what the Devices page shows. Fields that do not apply to a kind of device are left out or zero.",
	"Module":       "One controllable or readable part of a device (a relay, light, cover, input, thermostat, sensor, …). Its `key` is what the command endpoint takes.",
	"MeterSet":     "A group of readings (one meter, one sensor or one phase).",
	"MeterValue":   "One reading. `type` says what it is: W, VA, VAR (power), PF (power factor), V, I (A), FREQ (Hz), T/T1…T4 (°C), H/HD (% humidity), L (lux), BAT (% battery), …",
	"ResultLine":   "The outcome for one device of an action on several devices.",
	"ConfigForm":   "The current values of one settings section, for the devices asked for, as one form. Only the part of the section that applies is present.",
	"ChecklistRow": "One device of the configuration checklist. Each cell is a boolean (on/off), a string, a number, a list (Bluetooth) or null when it does not apply to the device.",
	"FirmwareRow":  "One device of the Firmware page: the versions the device found itself, and the progress of an update.",
	"Settings":     "ShellyLanMan's settings.",
	"Status":       "What the UI needs before anything else. Open (no login needed).",
}

var fieldDocs = map[string]string{
	"Device.id":              "Identity: the MAC address, upper case, no separators. Use it in paths and `ids`.",
	"Device.mac":             "The MAC address as the device reports it.",
	"Device.gen":             "Generation: `1` to `4`; `blu` (a BLU TRV) or `bth` (a BLU/BTHome device behind a gateway); `-` for an unmanaged Wi-Fi device.",
	"Device.typeId":          "The model key: the Gen1 type (SHPLG-S) or the Gen2+ app name (Plus1).",
	"Device.typeName":        "The model's name as the table shows it.",
	"Device.hostname":        "The host name (shellyplus1-aabbccddeeff).",
	"Device.name":            "The name set in the device, if any.",
	"Device.ip":              "IP address.",
	"Device.port":            "HTTP port of the device (80).",
	"Device.status":          "`online`; `offline`; `login` (the device wants credentials ShellyLanMan does not have); `reading` (refresh or reboot in progress); `error`; `ghost` (known from the archive, not seen this run); `searching` (being looked for after a rescan).",
	"Device.managed":         "false: unknown model or failed to initialise; ShellyLanMan shows it but cannot read its readings.",
	"Device.battery":         "Battery powered: it sleeps and answers rarely.",
	"Device.protected":       "The device asks for a password.",
	"Device.error":           "Why the status is `error` or `login`.",
	"Device.lastSeen":        "Unix milliseconds of the last successful contact.",
	"Device.ssid":            "The Wi-Fi network the device is on.",
	"Device.rssi":            "Wi-Fi signal in dBm.",
	"Device.cloudEnabled":    "The Shelly Cloud is switched on in the device.",
	"Device.cloudConnected":  "The device is connected to the Shelly Cloud.",
	"Device.mqttEnabled":     "MQTT is switched on in the device.",
	"Device.mqttConnected":   "The device is connected to its MQTT broker.",
	"Device.uptime":          "Seconds since the device started; -1 when unknown.",
	"Device.logMode":         "Where the device writes its log: NONE, FILE, MQTT, SOCKET, UDP or UNDEFINED.",
	"Device.internalTemp":    "Internal temperature in °C.",
	"Device.meters":          "Readings: power, voltage, temperature, … See MeterSet.",
	"Device.modules":         "The parts you can read and control. See Module.",
	"Device.layout":          "How the Command column draws the modules (a hint for user interfaces).",
	"Device.paused":          "Refreshing this device is paused (its log dialog is open).",
	"Device.rebootRequired":  "The device says it needs a restart (a setting changed, or a firmware update was loaded).",
	"Device.updateAvailable": "The device says a newer stable firmware exists. Beta alone does not count. What the device last found; the Firmware page's check refreshes it.",
	"Device.updateVersion":   "That version, when the device says which.",
	"Device.parent":          "BLU devices: the id of the gateway that hears it.",
	"Device.parents":         "BLU devices: other gateways that see it (host names).",
	"Device.relay":           "A BLU device a gateway only relays to the Shelly Cloud: read only.",
	"Device.note":            "Note from the archive.",
	"Device.keyword":         "Keyword from the archive.",

	"Module.kind":       "relay, light, rgb, rgbw, cct, rgbcct, cover, input, thermostat, cb (circuit breaker), camera or sensor.",
	"Module.index":      "Index of the part within its kind.",
	"Module.key":        "The key the command endpoint takes (`switch:0`, `color/0`, …).",
	"Module.label":      "Its name.",
	"Module.on":         "Relay or light is on.",
	"Module.brightness": "Light brightness, 0–100.",
	"Module.position":   "Cover position, 0–100.",
	"Module.target":     "Thermostat target temperature in °C.",
	"Module.rgb":        "Red, green and blue, 0–255.",
	"Module.white":      "White channel, 0–255.",
	"Module.tempK":      "Colour temperature in kelvin.",
	"Module.state":      "Cover state, or the text of a sensor.",
	"Module.events":     "The actions of an input that can be run (Command `event`).",

	"ResultLine.id":      "Device id.",
	"ResultLine.name":    "Host name of the device.",
	"ResultLine.result":  "`ok`, `fail` or `queued` (the device is offline: the action waits as a deferred task).",
	"ResultLine.message": "What went wrong.",

	"Command.key":        "`Module.key` of the part to control.",
	"Command.action":     "on, off, toggle, brightness (value 0–100), gain (0–100), white (0–255), color (rgb, white), temp (kelvin), mode (1 colour, 0 white), open, close, stop, position (0–100), target (°C), enable (1/0, thermostat), privacy (1/0, camera) or event (run the URLs of `Module.events[event]`).",
	"Command.value":      "The value of the action.",
	"Command.timer":      "Seconds after which a relay flips back (on, off, toggle).",
	"Command.transition": "Seconds a light takes for the change.",
	"Command.event":      "Index in `Module.events` (action `event`).",
	"Command.confirm":    "Needed to toggle a circuit breaker.",

	"ChecklistAction.ids":    "Devices to change.",
	"ChecklistAction.action": "eco, led, logs, ap, roaming, extender or autofw.",
	"ChecklistAction.value":  "The new state (on/off).",
	"ChecklistAction.mode":   "logs on Gen2+: `socket` or `mqtt`; autofw: `stable`, `beta` or `none`.",

	"FirmwareRow.known":     "The device has a firmware manager; archived and unmanaged devices only get an `any` update, queued.",
	"FirmwareRow.valid":     "The check succeeded.",
	"FirmwareRow.current":   "Installed version.",
	"FirmwareRow.stable":    "Newest stable version the device found.",
	"FirmwareRow.beta":      "Newest beta version the device found.",
	"FirmwareRow.preselect": "The stable version is newer than the installed one (what the page ticks).",
	"FirmwareRow.progress":  "Download progress in %; -1 unknown.",
	"FirmwareRow.queued":    "A deferred update is waiting for the device.",

	"FirmwareRequest.id":    "Device id.",
	"FirmwareRequest.stage": "`stable`, `beta`, or `any` (no information: queued, stable when it runs).",

	"IndexRow.source": "Where the version came from: `shelly` (Shelly's index) or `shelly-tools` (the archive).",
	"IndexRow.newer":  "The index has a newer stable version than the device runs.",

	"LocalLink.url":     "The download link a phone opens (valid until `expires`).",
	"LocalLink.qr":      "The link as a QR code, a PNG data URL.",
	"LocalLink.expires": "Unix milliseconds.",

	"RestoreSource.deviceId": "A backup kept on the server: the device it belongs to…",
	"RestoreSource.file":     "…and its file name (see `GET /api/v1/backups`).",
	"RestoreSource.upload":   "Or an uploaded `.sbk`, base64.",
	"RestorePlan.queue":      "The device is not reachable: the restore would be queued.",
	"RestoreResult.result":   "`ok`, `queued` or `fail`.",
	"RestoreResult.reboot":   "The restored settings need a reboot.",

	"ScanState.mode":     "Scan mode: `full`, `local`, `ip` or `offline`.",
	"ScanState.scanning": "An IP scan is running.",

	"Settings.language":           "Default language for browsers that have not chosen one.",
	"Settings.mqttSlow":           "Extra pause, in tenths of a second, after each device when MQTT settings are applied to several.",
	"Settings.backupKeep":         "Backups kept per device; older ones are deleted. 0 keeps all.",
	"Settings.phoneBaseURL":       "The address phones use for local firmware downloads (`http://host:port`); empty: the address the browser used.",
	"Settings.updateCheck":        "Release check on GitHub: `never` (default), `stable` or `all`.",
	"ScanSettings.mode":           "`full` (mDNS on all interfaces), `local` (mDNS on one), `ip` (ranges) or `offline` (archive only).",
	"ScanSettings.refreshSeconds": "Seconds between status refreshes while a browser is open.",
	"ScanSettings.configTics":     "Status refreshes per configuration refresh.",

	"Sample.t":       "Unix milliseconds.",
	"EMSeries.data":  "For each phase in turn: `[unix seconds, Wh]`.",
	"EMSeries.meter": "`em:0` or `em1:N`.",

	"InfoRequest.path":   "The request ShellyLanMan sends to the device (or its gateway).",
	"InfoResult.stored":  "The answer was kept from when the device was awake.",
	"APGuide.ssid":       "The access point's name.",
	"APGuide.assumed":    "The name is the device's default one, not read from it (the device could not be reached).",
	"APGuide.gen":        "`1`, or `2` for Gen2 and newer.",
	"APGuide.key":        "The key of the firmware index: the Gen1 type or the Gen2+ app.",
	"APGuide.model":      "The model's name.",
	"APGuide.mac":        "The MAC address, when the name carries it.",
	"APGuide.id":         "The device in the list, when it is there.",
	"APGuide.apEnabled":  "Whether the access point is switched on, read from the device. Absent when it could not be read.",
	"APGuide.open":       "Gen2+: the access point has no password. Absent when unknown.",
	"APGuide.recognised": "The model could be read.",
	"APGuide.joinQR":     "A QR code (PNG data URL) that makes a phone join the access point. Only for an open access point.",
	"APGuide.pageURL":    "Where the device's page is while the phone is on its access point.",
	"APGuide.pageQR":     "A QR code (PNG data URL) for that address.",
	"ModelChoice.gen":    "`1`, or `2` for Gen2 and newer.",
	"ModelChoice.key":    "The key of the firmware index.",
}
